# Generated by Django 5.1.7 on 2025-03-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('20-29', '20-29 years'), ('30-39', '30-39 years'), ('40-49', '40-49 years'), ('50-59', '50-59 years'), ('60+', '60 years or older')], max_length=10)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('family_history', models.BooleanField(help_text='Close relative had breast cancer')),
                ('family_history_age', models.IntegerField(blank=True, help_text='Age when relative was diagnosed', null=True)),
                ('previous_biopsies', models.BooleanField(default=False)),
                ('biopsy_results', models.BooleanField(blank=True, help_text='Were any biopsies abnormal?', null=True)),
                ('first_period_age', models.IntegerField(help_text='Age at first menstrual period')),
                ('first_pregnancy_age', models.IntegerField(blank=True, help_text='Age at first pregnancy', null=True)),
                ('hormone_therapy', models.BooleanField(default=False, help_text='Current/recent hormone therapy')),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
