# Generated by Django 5.1.7 on 2025-03-09 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_riskassessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='biopsy_results',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='family_history',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='family_history_age',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='first_period_age',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='first_pregnancy_age',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='hormone_therapy',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='previous_biopsies',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='conversation_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='key_factors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='recommendations',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
